dom:
  # 객실/요금 '한 줄(오퍼)' 컨테이너
  room_card:
    - css: "div[data-selenium='ChildRoomsList-room']"

  # room_card 내부/주변에서 뽑을 필드들
  fields:
    # 객실명(패키지/룸 그룹명): 가장 가까운 상위 MasterRoom 블록의 타이틀
    # → 코드에서 room_card의 조상으로 올라가 [data-selenium='MasterRoom']를 찾고,
    #    그 안의 [data-selenium='masterroom-title-name'] 텍스트를 읽어 배치
    room_name:
      - css: ":scope"                       # (프로그램에서 조상 탐색로직으로 처리)

    # 1박가(세금/봉사료 제외) - "캐시백 적용 후" 실제 노출가
    # 1) data-속성값(숫자) 우선, 2) 텍스트 보조
    price_per_night:
      - attr: "data-fpc-value"
        css: "[data-element-name='fpc-price-after-cashback']"
      - css: "span[data-selenium='PriceDisplay'] strong[data-ppapi='room-price']"

    # 총액(옵션): 버튼에 노출된 숙박일수(data-element-length-of-stay)를 곱해 계산
    price_total:
      - derived: "price_per_night * nights_from_button"

    # 플랜/혜택 배지 (무료취소, 조식 등)
    plan_badges:
      - css: ".ChildRoomsList-room-featurebuckets [data-testid='text']"
  price:
    - css: "span[data-component='Price'] span"
    - css: "span.final-price"
    - css: "span[data-selenium='finalPrice']"
  currency:
    - css: "body"
