project: pricing-probe
timezone: Asia/Seoul
run_every_hours: 3
concurrency:
  per_platform: 2
  global_max: 4
rates:
  requests_per_domain_per_second: 1.0
  jitter_seconds: [0.8, 2.2]
paths:
  data_dir: ./data
  logs_dir: ./logs
  secrets_dir: ./secrets
  runtime_dir: ./runtime
storage:
  format: csv
  save_html: true
  save_screenshot: true
  screenshot_format: webp
  keep_runs_days: 14
fallback:
  pipeline: [dom, ocr]
  ocr:
    lang: [ko, en]
    min_confidence: 0.75
validation:
  currency_allow: [KRW, USD]
  price_range:
    min: 0
    max: 100000000
