profiles:
  - id: "L0-KR-M"
    login: false
    region: "KR"
    user_agent: "mobile"
    accept_language: "ko-KR,ko;q=0.9"
    timezone: "Asia/Seoul"
  - id: "L0-KR-D"
    login: false
    region: "KR"
    user_agent: "desktop"
    accept_language: "ko-KR,ko;q=0.9"
    timezone: "Asia/Seoul"
  - id: "L0-US-M"
    login: false
    region: "US"
    user_agent: "mobile"
    accept_language: "en-US,en;q=0.9"
    timezone: "America/Los_Angeles"
  - id: "L0-US-D"
    login: false
    region: "US"
    user_agent: "desktop"
    accept_language: "en-US,en;q=0.9"
    timezone: "America/Los_Angeles"
  - id: "L1-KR-M"
    login: true
    region: "KR"
    user_agent: "mobile"
    accept_language: "ko-KR,ko;q=0.9"
    timezone: "Asia/Seoul"
  - id: "L1-KR-D"
    login: true
    region: "KR"
    user_agent: "desktop"
    accept_language: "ko-KR,ko;q=0.9"
    timezone: "Asia/Seoul"
  - id: "L1-US-M"
    login: true
    region: "US"
    user_agent: "mobile"
    accept_language: "en-US,en;q=0.9"
    timezone: "America/Los_Angeles"
  - id: "L1-US-D"
    login: true
    region: "US"
    user_agent: "desktop"
    accept_language: "en-US,en;q=0.9"
    timezone: "America/Los_Angeles"
network:
  proxy_pool:
    KR: "pool_kr"
    US: "pool_us"
ua_presets:
  mobile: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
  desktop: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
