dom:
  # 최신 PDP의 'price to pay' 계열 우선
  price_total:
    - css: "#corePriceDisplay_desktop_feature_div .a-price .a-offscreen"
    - css: "#apex_desktop .a-price .a-offscreen"
    - css: "#corePrice_feature_div .a-price .a-offscreen"
    # 레거시/대체 셀렉터
    - css: "#priceblock_ourprice"
    - css: "#priceblock_dealprice"
    - css: "#priceblock_saleprice"
    - css: "#price_inside_buybox"
    - css: "#tp_price_block_total_price"
    - css: "#newBuyBoxPrice"
  title_hint:
    - css: "#productTitle"
  currency_hint:
    - css: "body"
